# =============================================================================
# CONFIGGUARDIAN - SAMPLE CONFIGMAP
# -----------------------------------------------------------------------------
# This file contains ONLY fictitious data created for learning, testing and
# demonstration purposes.
# =============================================================================

apiVersion: v1
kind: ConfigMap

metadata:
  name: config-properties-ms-e
  namespace: desarrollo

data:
  SMTP_SERVER: smtp.demo.local
  SMTP_PORT: "587"
  SMTP_USER: demo_user
  SMTP_PASSWORD: demo_password
  SERVER_PORT: "8085"