apiVersion: v1
kind: ConfigMap

metadata:
  name: configguardian
  namespace: desarrollo

data:
  DATABASE_URL: jdbc:mysql://localhost:3306/configguardian
  DATABASE_USER: admin
  DATABASE_PASSWORD: password123
  PORT: "8080"
  TIMEOUT: "30"